# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages: 
  - stage: Build  
    jobs: 
     - job: Build_Artifact

       steps: 
       - task: CmdLine@2
         inputs:
          script: |
           cd ~
           ls -alrt
           mkdir -p ~/.ssh
           echo $(private_key) > ~/.ssh/id_rsa
           cat ~/.ssh/id_rsa
           sudo chomd -R 400 ~/.ssh/id_rsa
           #git clone git@github.com:manojbale/private.git

  - stage: 'Clone git repositories'
    jobs: 
     - job: 'Clone github private repository'
       steps:
       - task: CmdLine@2
         inputs:
          script: |
           ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
           git clone git@github.com:manojbale/private.git





