# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages: 
  - stage: Stage_Build
    jobs: 
     - job: Job_Build_Artifact

       steps: 
       - task: CmdLine@2
         displayName: 'generate private key'
         inputs:
          script: |
           cd ~
           ls -alrt
           mkdir -p ~/.ssh
           echo $(private_key) > ~/.ssh/id_rsa
           cat ~/.ssh/id_rsa
           sudo chmod -R 700 ~/.ssh/id_rsa
           echo $(public_key) > ~/.ssh/id_rsa.pub
           cat ~/.ssh/id_rsa.pub
           sudo chmod -R 700 ~/.ssh/id_rsa.pub
           #git clone git@github.com:manojbale/private.git

       - task: CmdLine@2
         displayName: 'Miscellaneous'
         inputs:
          script: |
           cd ~/.ssh/
           touch known_hosts
           ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
           hostname
           hostname -i
   
       - task: CmdLine@2
         displayName: 'Git clone command'
         inputs:
          script: |
           cat /etc/ssh/sshd_config | grep StrictModes
           #eval "$(ssh-agent -s)"
           #ssh-add -k
           #sshd -T
           #ssh-add ~/.ssh/id_rsa
           #ssh -o StrictHostKeyChecking=no
           #ssh -vT git@github.com
           #git clone git@github.com:manojbale/private.git





